package command

import (
	"fmt"

	"github.com/equinox-io/equinox"
)

// assigned when creating a new application in the dashboard
const EQUINOX_APP_ID = "app_cegQipmziT"

// public portion of signing key generated by `equinox genkey`
var EQUINOX_PUB_KEY = []byte(`
-----BEGIN ECDSA PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEA8ybKlGOZ7eb7cuVh1JAFTZ1J8UL4xwi
iGLpTfOHcaubIS1e9kyMFW89uKxzkBIGM1wG0y7FU1PEhjXR7nEThvEuiTMOF4ph
uQGA+FYmF7Ffb7Ib9TVtbmAvgyFBD1zZ
-----END ECDSA PUBLIC KEY-----
`)

type (
	UpdateCommand struct {
		*CommandMeta
	}
)

func (c *UpdateCommand) Run(args []string) int {
	var err error

	const (
		YOU_ARE_UP_TO_DATE = "You are running the latest version. Thank you for staying up-to-date!"
	)

	var options equinox.Options
	if err = options.SetPublicKeyPEM(EQUINOX_PUB_KEY); err != nil {
		return c.ReturnError(err)
	}

	// check for update
	var resp equinox.Response
	if resp, err = equinox.Check(EQUINOX_APP_ID, options); err != nil {
		if err == equinox.NotAvailableErr {
			fmt.Println(YOU_ARE_UP_TO_DATE)
			return 0
		}
		return c.ReturnError(err)
	}

	// do not mistakenly update the developer build
	if resp.ReleaseVersion == c.AppVersion {
		fmt.Println(YOU_ARE_UP_TO_DATE)
		return 0
	}

	// fetch the update and apply it
	err = resp.Apply()
	if err != nil {
		return c.ReturnError(err)
	}

	fmt.Printf("Updated to new version: %s\n", resp.ReleaseVersion)

	return 0
}

func (c *UpdateCommand) Help() string {
	return "Usage: ./nefertiti update"
}

func (c *UpdateCommand) Synopsis() string {
	return "Check for a new version."
}
