package binance

const (
	WEIGHT_ALL_ORDERS                 = 10
	WEIGHT_CANCEL_ORDER               = 1
	WEIGHT_CREATE_OCO_ORDER           = 1
	WEIGHT_CREATE_ORDER               = 1
	WEIGHT_EXCHANGE_INFO              = 10
	WEIGHT_OPEN_ORDERS_WITH_SYMBOL    = 3
	WEIGHT_OPEN_ORDERS_WITHOUT_SYMBOL = 40
	WEIGHT_TICKER_24H_WITH_SYMBOL     = 1
	WEIGHT_TICKER_24H_WITHOUT_SYMBOL  = 40
)
